
  - everything in one file
  - default config
  - with over-riding options
  - emodl template;
  .format(with teh yaml

- experiment parameters
- fixed parameters
    - inc social distancing
- sampled parameters
- seed for random number generator

